---
- name: Install Docker and Docker Compose Offline
  hosts: localhost
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Copy Docker packages to remote server
      ansible.builtin.copy:
        src: "/home/{{ansible_user}}/Downloads/"
        dest: "{{ package_path }}"
        mode: "0644"

    - name: Install Docker dependencies
      ansible.builtin.apt:
        deb: "{{ package_path }}{{ containerd_version }}"
    
    - name: Install Docker CE
      ansible.builtin.apt:
        deb: "{{ package_path }}{{ docker_ci_version }}"

    - name: Install Docker CE CLI
      ansible.builtin.apt:
        deb: "{{ package_path }}{{ docker_cli_version }}"
    
    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Copy Docker Compose binary
      ansible.builtin.copy:
        src: "/home/{{ansible_user}}/docker-offline/{{ docker_compose_version }}"
        dest: "{{ package_path }}{{ docker_compose_version }}"
        mode: "0755"

    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_version_output
      changed_when: false

    - name: Print Docker version
      ansible.builtin.debug:
        msg: "{{ docker_version_output.stdout }}"

    - name: Verify Docker Compose installation
      ansible.builtin.command: docker compose --version
      register: compose_version_output
      changed_when: false

    - name: Print Docker Compose version
      ansible.builtin.debug:
        msg: "{{ compose_version_output.stdout }}"

- name: Add current user to docker group
  become: yes
  hosts: all
  tasks:
    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Refresh group membership for current session (needs relogin)
      shell: newgrp docker
      args:
        executable: /bin/bash
      when: ansible_user_id != 'root'
