---
- name: Uninstall Docker from Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Stop Docker service
      systemd:
        name: docker
        state: stopped
      ignore_errors: yes

    - name: Uninstall Docker packages
      apt:
        name:
          - docker.io
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove Docker directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /etc/docker
        - /var/run/docker.sock

    - name: Remove Docker group
      group:
        name: docker
        state: absent

    - name: Clean up unused dependencies
      apt:
        autoremove: yes
        purge: yes
        update_cache: yes

